### ISSUE TITLE
Update Website

### ISSUE THREAD

**Issue by gen1e** [Women-in-Computing-at-RIT/taskbox#6]
We need to put up a blurb and a link to the Magic Mirror docs @aviggiano836 

We also need to put a link to the WiC Arcade cabinet for our public facing documentation: https://github.com/Women-in-Computing-at-RIT/RaspberryPiArcadeCabinet

**Comment by CraftSpider** [comment]
Idea: Make the names on each of the projects link to their pages, so it's like `2017: <a>Magic Mirror</a>`
Pros: easy documentation linking, fits the existing layout.
Cons: Might be non-obvious/confusing, if not all have documentation things won't match.

**Comment by ldidonato** [comment]
It already exists. [http://wic.rit.edu/projects.php](http://wic.rit.edu/projects.php) I just need a blurb for the mirror and links for the other projects. thanks.

**Comment by gen1e** [comment]
We have blurbs, @ldidonato needs to add the doc links
Magic Mirror: https://github.com/Women-in-Computing-at-RIT/Magic-Mirror
Arcade Cabinet: https://github.com/Women-in-Computing-at-RIT/RaspberryPiArcadeCabinet

**Comment by gen1e** [comment]
http://wic.rit.edu/projects.php Docs show up now. Thanks guys!
